---
language: python
python: "2.7"
os: linux
dist: trusty
env:
  - ansible_version="2.0.0.2"
  - ansible_version="2.0.2.0"
  - ansible_version="2.1.3.0"
  - ansible_version="2.2.0.0"

# Use the new container infrastructure
sudo: required

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  # Install ansible
  - pip install -I "ansible==$ansible_version"

install:

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

script:
  # Basic role syntax check
  # Test Demo case 1
  - ansible-playbook tests/test.yml -i tests/inventory
  # test login pages
  - curl -i -s --insecure --data "user=ncadmin&password=" https://localhost/index.php/login | egrep -q "Location:.*/apps/files/"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
